Introduction to Pytorch

In [1]:
# !pip install torch "for installing pytorch package"

In [2]:
import torch

torch.__version__

'2.5.1+cpu'

## Introduction to Tensors 

Tensors are the fundamental building block of machine learning. Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

Example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width.   

![image.png](https://camo.githubusercontent.com/1ed28f5c8dc4e8d8390c00f2ab9407b3dddeab375d3657b70310f6699bdb6890/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d7264626f75726b652f7079746f7263682d646565702d6c6561726e696e672f6d61696e2f696d616765732f30302d74656e736f722d73686170652d6578616d706c652d6f662d696d6167652e706e67)

In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for colour_channels, height and width.


<b> A Formal Defination : A Tensor is a mathematical object that helps describe complex relationships between physical quantities, such as forces, energies, and velocities.

In Pytorch everything is refered to as Tensors.
</b> 


<b> Creating Tensor </b>

Tensor can be created using `torch.tensor()`

![Tensors](https://www.kdnuggets.com/wp-content/uploads/scalar-vector-matrix-tensor.jpg)

In [3]:
scalar = torch.tensor(5)

scalar # single dimension number

tensor(5)

In [4]:
scalar.item() # Gets tensor back as a python 'int'

5

In [5]:
vector =torch.tensor([5 , 5])

vector # single dimension vector [ xi , yj ]

tensor([5, 5])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[5 , 5] , [10 , 10]])

matrix

tensor([[ 5,  5],
        [10, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1][0] # indexing in matrix [row][col]

tensor(10)

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
Tensor = torch.tensor([[ 
                [1 , 2 , 3],
                [3 , 6 ,9],
                [4 , 2 , 5]
                ]])

Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 2, 5]]])

In [13]:
Tensor.ndim

3

In [14]:
Tensor.shape 

torch.Size([1, 3, 3])

![Explanation of tensor.shape's output](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

some example

In [15]:
ex = torch.tensor([
    [
        [1 , 2 , 3 , 4],
        [5 , 6 , 7 , 8],
        [ 9 , 10 , 11 , 12]
    ],
    [
    [5 , 6 , 7 , 8],
    [ 9 , 10 , 11 , 12],
    [1 , 2 , 3 , 4]
    ]
])

In [16]:
ex.shape # 2 lists with 3 lists inside each inside-list having 4 scalars

torch.Size([2, 3, 4])

<b> Random Tensors </b>

Why ? : Because the way many nerual networks learn is that they start learning with tensors full of random numbers and then adjust those random numbers
        to better represent data.

`Start with random nums -> look at data -> update random nums -> look at data -> update random nums .....`

In [17]:
# Creating a random tensor [rows,cols]

# rand_tensor = torch.rand([5 , 5])
# rand_tensor = torch.rand([10 , 10 , 10])
# rand_tensor = torch.rand([1 ,  3 , 4])
rand_tensor = torch.rand([ 3 , 3 , 3])
rand_tensor

tensor([[[0.8421, 0.6540, 0.5729],
         [0.7738, 0.3529, 0.5053],
         [0.4078, 0.7830, 0.6103]],

        [[0.4920, 0.5546, 0.5528],
         [0.2061, 0.7444, 0.8146],
         [0.1153, 0.9652, 0.2420]],

        [[0.7413, 0.5744, 0.0195],
         [0.7143, 0.9405, 0.0562],
         [0.7563, 0.0066, 0.8760]]])

In [18]:
rand_tensor.dim()

3

In [19]:
# Example of a random image tensor

img_tensor = torch.rand([244 , 244 , 3]) # height , width and 3 color channels(RGB) of image exampl

# OR

# img_tensor = torch.rand(size=(244 , 244 , 3))

In [20]:
img_tensor.dim()

3

In [21]:
img_tensor.size()

torch.Size([244, 244, 3])

<b>Tensor of Zeros and Ones </b>

In [22]:
zeros_tensor = torch.zeros([2 , 2])
# Trying complex example
# zeros_tensor = torch.zeros([3 , 3 , 3 , 3])
zeros_tensor

tensor([[0., 0.],
        [0., 0.]])

In [23]:
ones_tensor = torch.ones([2 , 2])
# Trying complex example
# ones_tensor = torch.ones([2 , 2 , 2 , 2 , 2])
ones_tensor 

tensor([[1., 1.],
        [1., 1.]])

<b> Generating Tensor with `torch.arange()` </b>

In [24]:
range_tensor = torch.arange(1 , 11)
range_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
zeros_range_tensor = torch.zeros_like(range_tensor)
zeros_range_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ones_range_tensor = torch.ones_like(range_tensor)
ones_range_tensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<b>Tensors of various numerical datatypes </b>

In [27]:
normal_tensor = torch.tensor([2. , 3. , 4.]) # normal dtype of tensor is `tensor.float32`
normal_tensor.dtype

torch.float32

In [28]:
# the `dtype` parameter in the torch.tensor() can be used to manipulate dtype of the tensor generated.
int_tensor = torch.tensor([5 , 6 , 7 ,99] , dtype=torch.int64)
int_tensor.dtype

torch.int64

In [29]:
double_tensor = torch.tensor([5 , 6 , 7 ,99] , dtype=torch.double ) # torch.double = torch.float64
double_tensor.dtype

torch.float64

<b>Getting properties of Tensor </b>

In [30]:
Example_Tensor = torch.rand([2 , 3])
Example_Tensor

tensor([[0.3102, 0.5678, 0.6505],
        [0.9196, 0.5442, 0.3189]])

In [31]:
Example_Tensor.shape

torch.Size([2, 3])

In [32]:
Example_Tensor.dtype

torch.float32

In [33]:
Example_Tensor.device

device(type='cpu')

<b> Manipulating Tensors ( Operation on Tensors ) : </b> 

Addition , Substraction , Multiplication (element-wise) , Division , Matrix-Multiplication

In [34]:
TENSOR = torch.tensor([1 , 2 , 3] , dtype=torch.float32)
TENSOR

tensor([1., 2., 3.])

In [35]:
TENSOR + 100 # or torch.add()

tensor([101., 102., 103.])

In [36]:
TENSOR - 1 # or torch.substract()

tensor([0., 1., 2.])

In [37]:
TENSOR // 3 # or torch.divide()

tensor([0., 0., 1.])

In [38]:
# Element-Wise Multiplication ( can be done with `torch.mul()` )

print(TENSOR , " * " , TENSOR)
print(f"Equals to : " , TENSOR*TENSOR)

tensor([1., 2., 3.])  *  tensor([1., 2., 3.])
Equals to :  tensor([1., 4., 9.])


In [39]:
matrix = torch.tensor([[2 , 3] , [4 , 5]])
matrix

tensor([[2, 3],
        [4, 5]])

In [40]:
# Matrix Multiplication
torch.matmul(matrix , matrix) # or matrix @ matrix
# this method takes less time because it is optimized with vectorization

tensor([[16, 21],
        [28, 37]])

<b> Rules for Matrix multiplication :

1. Inner Dimensions of two vectors must match [ i.e (2 , 3) * ( 3 , 2) works but (3 , 3) * ( 2 , 3) won't work ]

2. Resulting Matrix has shape of Outer Dimension [ i.e (2 , 3)* (3 , 2) will give us a 2*2 matrix ] </b>

<b> Most Common Shape Errors </b>

In [41]:
A = torch.tensor([[1 , 2 ] ,[3 , 4] , [5 , 6] ])
B = torch.tensor([[7 , 8 ] , [9 , 10 ] , [11 , 12]])

In [42]:
A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [43]:
B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [44]:
# torch.mm(A , B) # Can't be multiplied because of different inner dimension. To fix it we can use `T`
torch.mm(A , B.T) # `.T` means transpose

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [45]:
torch.mm(A.T , B)

tensor([[ 89,  98],
        [116, 128]])

<b>Tensor Aggregation ( sum() , min() , max() , etc..)</b>

In [64]:
ten = torch.tensor([x for x in range(10 , 100 , 10)])
ten

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
ten.max() # or torch.max(ten)

tensor(90)

In [ ]:
ten.argmax() # returns index of the max. value

tensor(8)

In [72]:
ten.argmin() # returns index of the min. value

tensor(0)

In [ ]:
ten.min() # or torch.min(ten)

tensor(10)

In [ ]:
ten.sum() # or torch.sum(ten)

tensor(450)

In [ ]:
# ten.mean() # .mean() needs the tensor's dtype to be float32 onwards

ten.type(torch.float64).mean() # or torch.mean(ten.type(torch.float64))

tensor(50., dtype=torch.float64)

In [102]:
Tensor_X = torch.arange(1. , 11.)
Tensor_X , Tensor_X.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

<b>Reshaping a Tensor</b>

In [84]:
Tensor_X.reshape(10 , 1)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [85]:
Tensor_X.reshape(5 , 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [86]:
Tensor_X.reshape(2 , 5)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
# Viewing Tensor
Tensor_X.view(5 , 2)
#  `view` shares the same memory where original tensor is located. Thus changing the view will also change the original tensor

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

<b>Stacking Tensors</b>

In [90]:
torch.stack([Tensor_X , Tensor_X])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [91]:
torch.stack([Tensor_X , Tensor_X], dim=1)

tensor([[ 1.,  1.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.],
        [10., 10.]])

<b>Squeezing and Unsqueezing</b>

To squeeze is to remove `1` dimension from tensor while to unsqueeze is to add `1` dimension to tensor.

In [114]:
Tensor_X = torch.rand([1 , 3 , 3])
Tensor_X

tensor([[[0.0824, 0.1090, 0.1946],
         [0.6705, 0.1458, 0.6487],
         [0.5654, 0.6596, 0.3923]]])

In [115]:
Tensor_X.shape

torch.Size([1, 3, 3])

In [120]:
squ_ten_x = Tensor_X.squeeze()
squ_ten_x

tensor([[0.0824, 0.1090, 0.1946],
        [0.6705, 0.1458, 0.6487],
        [0.5654, 0.6596, 0.3923]])

In [ ]:
squ_ten_x.shape # removes single dimension from the tensor

torch.Size([3, 3])

In [124]:
unsqu_ten_x = Tensor_X.unsqueeze(dim=1)
unsqu_ten_x

tensor([[[[0.0824, 0.1090, 0.1946],
          [0.6705, 0.1458, 0.6487],
          [0.5654, 0.6596, 0.3923]]]])

In [125]:
unsqu_ten_x.shape

torch.Size([1, 1, 3, 3])

<b>Premuting a Tensor</b>

`.permute()` returns a `view()` to the tensor premuted to a different dimensions.

In [130]:
premuted_tensor = torch.permute(Tensor_X ,(1 , 2 , 0)) # takes in tuple of indices of tensor.shape
premuted_tensor

tensor([[[0.0824],
         [0.1090],
         [0.1946]],

        [[0.6705],
         [0.1458],
         [0.6487]],

        [[0.5654],
         [0.6596],
         [0.3923]]])

In [131]:
premuted_tensor.shape

torch.Size([3, 3, 1])

In [133]:
Tensor_X[0 , 0 , 0] = 4873837

In [ ]:
premuted_tensor # Values of premuted_tensor changes.

tensor([[[4.8738e+06],
         [1.0900e-01],
         [1.9456e-01]],

        [[6.7053e-01],
         [1.4583e-01],
         [6.4871e-01]],

        [[5.6537e-01],
         [6.5960e-01],
         [3.9229e-01]]])