<a href="https://colab.research.google.com/github/AdityaMohite47/Machine-Learning-With-PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
  - Tensor is a multi-dimensional matrix containing elements of a single data type.

  - Similar to Numpy Array but they work faster and better with GPU , Thus these are more suitable for Deep Learning.

  - A Tensor's default datatype is float32.


In [3]:
import torch
import numpy as np # for comparing with a Tensor with Numpy Array

Numpy Array

In [7]:
nparray = np.random.rand(3 , 4)
nparray


array([[0.14488217, 0.5143325 , 0.94978082, 0.40241448],
       [0.79641736, 0.10012683, 0.89281377, 0.11802322],
       [0.20804778, 0.85272752, 0.94417821, 0.14437439]])

In [8]:
nparray.dtype

dtype('float64')

Tensor

In [9]:
tensor = torch.randn(3 , 4) # A 2-D tensor

tensor

tensor([[ 0.6889, -1.1097,  1.1352, -0.3601],
        [ 0.6152, -0.3563, -1.1050,  0.0752],
        [ 0.2980, -0.8682, -0.2229, -0.8602]])

In [10]:
tensor.dtype

torch.float32

In [12]:
tensor3D = torch.zeros(2 , 3 , 4) # A 3-D tensor
tensor3D

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Creating tensor out of a Numpy Array

In [13]:
np_to_tensor = torch.tensor(nparray)

np_to_tensor

tensor([[0.1449, 0.5143, 0.9498, 0.4024],
        [0.7964, 0.1001, 0.8928, 0.1180],
        [0.2080, 0.8527, 0.9442, 0.1444]], dtype=torch.float64)

Tensor and Dimensions

- 0D Tensor (Scalar): Just a number. For example, 5.

- 1D Tensor (Vector): A list or array of numbers. For example, [1, 2, 3].

- 2D Tensor (Matrix): A grid of numbers. For example :
[ [1, 2],
 [3, 4] ]

- 3D Tensor : Think of it as a stack of 2D matrices.
For example imagine 3 2D matrices stacked together :

[
    [
        [1, 2], [3, 4]
    ],
    [
        [5, 6], [7, 8]
    ],
    [
        [9, 10], [11, 12]
    ]
]

